### ISSUE TITLE
Bad request :  https://device-manager.scratch.mit.edu:20110

### ISSUE THREAD

**Issue by Mijsoot** [kawasaki/bluepy-scratch-link#5]
I think the URL don't work anymore :  https://device-manager.scratch.mit.edu:20110

Have you got some idea ?

Thierry

**Comment by kawasaki** [comment]
Hi @Mijsoot,
With my Linux system and home network, bluepy-scratch-link is working well with the URL. Do you observe any error or anything unexpected about that URL?

**Comment by Mijsoot** [comment]
![Bluepy_scratch_link_Scratch_url_error_14_02_20](https://user-images.githubusercontent.com/22812111/74519951-f8302100-4f16-11ea-9f02-1b237ff9486a.jpg)

Hi @kawasaki , 
You can what i mean on the attached scrennshot

**Comment by kawasaki** [comment]
Hi @Mijsoot ,
Hmm, I see. Then I would like to confirm two things.
Firstly, I assume you already started bluepy-scratch-link with  "sudo ./scratch_link.py" command and that command is running when you saw the error. Is the command running when you saw the error?
Secondly, what happens when you do "ping device-manager.scratch.mit.edu" or "nslookup device-manager.scratch.mit.edu" with you system? With my system, these commands show address 127.0.0.1.

**Comment by kawasaki** [comment]
No response for a couple of months. Let me close this issue. If this is still the problem, please open another issue.
